permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Aaron Sander"
  description: |
    Aaron Sander's portfolio website.
  font_url: "https://fonts.googleapis.com/css?family=Lora:400,400i,700|Raleway:400,500,600,700,800,900&display=swap"
  colors:
    accent: "--color-primary"
    patterns:
      brand.logos: "--color-primary-light"
    rationales:
      typefaces.primary: |
        Raleway was selected as the primary typeface because it is bold and has a lot of choices in font weight and has a lot of personality.
      typefaces.secondary: |
        Lora was selected as the secondary typeface because it compliments the weight of Raleway.
      colors.primary: |
        Having black and white as the primary colours keeps a clean feel and gives a good base to add in the accent colours.
      colors.secondary: |
        Yellow and blue were chose because there are bright but complimentary colours.
collections:
  previews:
  contentbanner:
