title: "Buttons"
description: |
  Used to link to functioal sites or the pattern library.

patterns:
  site:
    title: "Links Button"
    description: |
      Links to Pages
    fields:
      - name: data
        type: object
        data:
          source: "site.buttons[0]"
          type: Button
