title: "Navigation"
description: |
  This is the main header on all my pages. It includes my logo, a link to farther down the page to my work, a link to my about which brings you even farther down my page to it. The last link in my nav is a contact that contains my email.
